#!/bin/sh

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

DIR="$HOME/.config/"
# $HOME/bin/eww close-all;
rofi \
	-show drun \
	-modi run,drun,ssh \
	-scroll-method 0 \
	-drun-display-format "{name}" \
	-terminal alacritty \
	-kb-cancel Escape\
	-theme "$DIR"/rofi/themes/launcher.rasi \
	-config "$DIR"/rofi/config.rasi &

paplay $HOME/.local/share/sounds/notification-3.ogg &
